name: testing
on:
  pull_request:
    branches: [main]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python: [3.9.12]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: checkout to current branch
        run: git checkout ${{ env.BRANCH }}

      - name: Install non-python dependencies on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y
          # pytest-qt's dependency
          sudo apt-get install -y libgles2-mesa-dev
          # explorepy's dependency
          sudo apt-get install libbluetooth-dev
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # install exploredesktop with its test dependencies
          pip install -e .[test]
      - name: Run pytest
        run: python -m pytest --import-mode=append
