name: testing
on: [workflow_dispatch]
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python: [3.9.12]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: checkout to current branch
        run: git checkout ${{ env.BRANCH }}
        
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          # install dependencies
          pip install pytest
          pip install pytest_qt
          pip install pyside6
          sudo apt-get update -y
          # pytest-qt's dependency
          sudo apt-get install -y libgles2-mesa-dev
      - name: Run pytest
        run: |
          pytest
